name: ttesler
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  infinite_scroll_pagination: ^4.0.0
  dio: ^5.4.0
  riverpod: ^2.5.0
  riverpod_generator: ^2.3.11
  json_serializable: ^6.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
